sonar.projectKey=jorgelopez04_BackendValidacion
sonar.organization=jorgelopez04
sonar.token=966a5b64d7641a61e3f43aa88a282e5b40e3e84e

# Definimos la raíz para que el scanner encuentre todo
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8

# INCLUSIONES: Solo estos archivos sumarán al porcentaje de coverage
sonar.inclusions=**/products.service.ts, **/orders.service.ts, **/tasks.service.ts

# Definimos dónde están las pruebas específicamente
sonar.test.inclusions=**/*.spec.ts

# Cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones adicionales para limpiar el dashboard
sonar.exclusions=**/*.module.ts, **/*.dto.ts, **/*.entity.ts, **/main.ts, src/auth/**