sonar.projectKey=jorgelopez04_BackendValidacion
sonar.organization=jorgelopez04
sonar.token=966a5b64d7641a61e3f43aa88a282e5b40e3e84e

# Definimos la raíz del código y las pruebas
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8

# Definimos qué archivos son pruebas
sonar.test.inclusions=**/*.spec.ts

# Ruta al reporte generado por Jest
sonar.javascript.lcov.reportPaths=src/coverage/lcov.info

# EXCLUSIONES DE ANÁLISIS: No se suben a SonarQube
sonar.exclusions=**/coverage/**#,**/employees.service.ts,**/customers.service.ts,**/categories.service.ts,**/flows.service.ts,**/roles.service.ts

# EXCLUSIONES DE COBERTURA: Se analizan (calidad), pero no restan porcentaje de cobertura
# Esto ignora DTOs, Entidades puras y Boilerplate de NestJS (Líneas 30, 33, 36, etc.)
