sonar.projectKey=jorgelopez04_BackendValidacion
sonar.organization=jorgelopez04
sonar.token=966a5b64d7641a61e3f43aa88a282e5b40e3e84e

# Definimos la raíz para que el scanner encuentre todo
sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8

# Definimos dónde están las pruebas específicamente
sonar.test.inclusions=**/*.spec.ts

# Cobertura (Asegúrate de que esta ruta coincida con tu carpeta de Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# EXCLUSIONES REDUCIDAS: Ahora solo ignoramos archivos de configuración 
# y boilerplate que no tienen lógica de negocio.
sonar.exclusions=**/*.module.ts, **/*.dto.ts, **/main.ts